### ISSUE TITLE
Question: What is the POS.csproj in this sample for?

### ISSUE THREAD

**Issue by MaxWilson** [microsoft/Dynamics365Commerce.ScaleUnit#12]
The POS.csproj in this sample doesn't build an installer for ModernPOS, like the InStore sample does. What is the POS project in this solution for and when would you want to use it? Is this for Cloud POS?

Asking because I originally followed this sample to port my Modern POS extension to CommerceSDK, but then couldn't find an installer. I'm pretty sure now I should have been following the InStore PackagingSamples instead (https://github.com/microsoft/Dynamics365Commerce.InStore/tree/release/9.35/src/PackagingSamples/ModernPos).

**Comment by rizworks** [comment]
Yes, it's for CloudPOS. You can add mpos installer project into solution and it will build the installer for you. Personally, I have combined the instore and CSU projects into a single repo and it helps streamline build and process but it all depends on how you want to manage the installer and updates.

**Comment by MaxWilson** [comment]
Could you share an example? Do I have to use VS 2017 and a .jsproj, or is adding an MPOS installer project enough?

**Comment by lukedgr** [comment]
The CPOS project in the scale unit sample is for Cloud POS extensions that can then be packaged into the RCSU deployable package or the In Store Scale Unit extension installer.
