### ISSUE TITLE
Question: about the access to the POS Url (Commerce SDK) from the other machine.

### ISSUE THREAD

**Issue by mauroschnider** [microsoft/Dynamics365Commerce.ScaleUnit#13]
Hi all

We had installed the new Commerce SDK in a Cloud Hosted (Dev) environment, where the HQ is the same Cloud Hosted Environment.

I have a question about the access to the POS Url from the other machine.

Can you tell me if we have any possible access to the POS Url (https://XXXXXXX:446/pos/#) from outside the RDP (Cloud Hosted Environment)? 

This alternative helps our consultants to carry out the tests in a more productive way.

Thank you in advance!

**Comment by Pikhulya** [comment]
Any customizations of an environment beyond the provisioning of it are not supported, anything else the customer wants is up to them, and can possible impact our ability to service such an environment.
