### ISSUE TITLE
Request: Expose Microsoft.Dynamics.Commerce.Runtime.Data.DataCacheAccessor in public packages

### ISSUE THREAD

**Issue by yobryon** [microsoft/Dynamics365Commerce.ScaleUnit#14]
We would like to be able to (continue to) use the L2 caching framework to cache data frequently used in CRT extensions, however, the Microsoft.Dynamics.Commerce.Runtime.DataManagers library is not included in the public package set. Can we maybe get it on the roadmap to make this accessible one way or another?

**Comment by Pikhulya** [comment]
As of now there are no plans to make that assembly part of the SDK, we are researching some options but there are no specific decisions yet, therefore, please plan building and maintaining the cache functionality yourself.
