### ISSUE TITLE
Is there a reference for all Commerce classes and their namespaces? Question about migrating some classes.

### ISSUE THREAD

**Issue by brtubb-patagonia** [microsoft/Dynamics365Commerce.ScaleUnit#16]
We are using an ISV solution that can take a long time to get updates on. We've requested they move to the CommerceSDK, but that may take months before it materializes. Looks like we'll need to migrate it in the meanwhile.

There are several classes/namespaces the ISV previously referenced in the RetailSDK but I'm not seeing in the CommerceSDK. What's the best way to find these new namespaces? I've tried adding most of the packages in Nuget to the project, but no luck.

Namespaces missing?
* Microsoft.Dynamics.Commerce.Runtime.TransactionService;
* Microsoft.Dynamics.Commerce.Runtime.DataServices.SqlServer;

Classes missing?
* TransactionServiceClient
* DatabaseErrorCodes
* SalesTransactionDataService

There is an older reference document for the older RetailSDK, but I'm not seeing it for D365 with the CommerceSDK. If there is a similar link, can you point me to it?
https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/crt-ref/net-framework-classes-for-microsoft-dynamics-ax-commerce-runtime

**Comment by Pikhulya** [comment]
The extension needs to be re-written to not reference those classes as they were not supposed to be referenced, please see more details [here](https://github.com/microsoft/Dynamics365Commerce.ScaleUnit/issues/5) which also includes a link to the documentation.

@mugunthanm - FYI.

**Comment by brtubb-patagonia** [comment]
Writing for future folks who may need a workaround - there is a short term workaround. So far we’ve been able to get the extension project to build by copying over, from the RetailSDK, the specific .dll files needed for the missing classes. _Finding_ the dlls for the missing classes is a bit challenging, but it does work in 10.0.24.

Inspiration:
https://www.yammer.com/dynamicsaxfeedbackprograms/#/threads/show?threadId=1547928521146368
