### ISSUE TITLE
Error while debugging ScaleUnit code in IIS Hosted mode

### ISSUE THREAD

**Issue by vkommuri2897** [microsoft/Dynamics365Commerce.ScaleUnit#18]
I am getting following error when i debug in IIS Hosted.

The certificate with identifier used to sign the client assertion is not registered on application. [Reason - The key was not found., Thumbprint of key used by client: '3705A3A73DEDAB44AC718A6AF8ED716A028582AD'
Please visit the Azure Portal, Graph Explorer or directly use MS Graph to see configured keys for app Id '32d7f9e2-f3d9-451d-b9e7-e30c50ca89d2'
[Installation-20220818.txt](https://github.com/microsoft/Dynamics365Commerce.ScaleUnit/files/9380286/Installation-20220818.txt)

**Comment by Pikhulya** [comment]
@vkommuri2897 , it means you didn't register the certificate with your AAD application, one of the ways to do that is described in [Assigning a certificate to an AAD application](https://community.dynamics.com/ax/b/axforretail/posts/introducing-sealed-installers#mcetoc_1fgi17hnmc)
