### ISSUE TITLE
An database error occurred when selecting from RetailStoreTable RCSU IIS Hosted

### ISSUE THREAD

**Issue by MuhammadUmairSiddiqui** [microsoft/Dynamics365Commerce.ScaleUnit#19]
Hi Team,

I am facing this issue while upgrading to RCSU Sealed.

Database error 'Unknown' occurred for 'execute query '[ax].[RETAILSTORETABLE]''. The SELECT permission was denied on the object 'RETAILSTORETABLE', database 'RetailChannelDatabase', schema 'ax'.

**Comment by Pikhulya** [comment]
Looks like your extension directly accesses the aforementioned table from within C#, the version 10.0.30 makes it possible but ideally consider to change your extension to never access tables directly from within C#, instead create Views/Stored Procedures  accessing the table you need and invoke those Views/Stored Procedures from within C#.
