### ISSUE TITLE
ScaleUnit project build fails if publisher name in repo.props contains special chars

### ISSUE THREAD

**Issue by andyNewnham** [microsoft/Dynamics365Commerce.ScaleUnit#2]
**Issue details:**
The Publisher property in the repo.props file should match the publisher of the code signing certificate you are using. (This is especially crucial in the POS solution, as it is validated on POS Extension install). For most code signing certificates, the publisher contains not only the CN, but also organization name, location and country. The correct format is for those values to be separated by a comma.
`<Publisher Condition="'$(Publisher)' == ''">CN=Contoso Ltd.</Publisher>`

During the build of the Scale Unit CS Project, the MS build targets for the project (Microsoft.Dynamics.Commerce.Sdk.ScaleUnit.targets), at line 90, attempts to replace the publisher name in the manifest file. 

```
Lines="$([System.IO.File]::ReadAllText(
        $(ManifestFile)).Replace(%(CustomManifestDataToReplace.Identity), %(CustomManifestDataToReplace.ReplacementValue)))"
```

**Error Message:**
If the publisher contains special characters (e.g. comma), the build will fail with the following error: 
```
ScaleUnit -> C:\XXX\ScaleUnit\src\ScaleUnitSample\ScaleUnit\bin\Release\netstandard2.0\ScaleUnit.dll
C:\Users\XXX\.nuget\packages\microsoft.dynamics.commerce.sdk.scaleunit\9.30.21211.6\build\Microsoft.Dynamics.Commerce.Sdk.ScaleUnit.targets(90,7): error MSB4184: The expression ""{
C:\Users\XXX\.nuget\packages\microsoft.dynamics.commerce.sdk.scaleunit\9.30.21211.6\build\Microsoft.Dynamics.Commerce.Sdk.ScaleUnit.targets(90,7): error MSB4184:     "sdkVersion": "9.28.0.0",
C:\Users\XXX\.nuget\packages\microsoft.dynamics.commerce.sdk.scaleunit\9.30.21211.6\build\Microsoft.Dynamics.Commerce.Sdk.ScaleUnit.targets(90,7): error MSB4184:     "customPackageName": "Contoso Scale Unit Example Commerce Customization",
C:\Users\XXX\.nuget\packages\microsoft.dynamics.commerce.sdk.scaleunit\9.30.21211.6\build\Microsoft.Dynamics.Commerce.Sdk.ScaleUnit.targets(90,7): error MSB4184:     "customPackageDescription": "MANIFEST_CUSTOM_DESCRIPTION",
C:\Users\XXX\.nuget\packages\microsoft.dynamics.commerce.sdk.scaleunit\9.30.21211.6\build\Microsoft.Dynamics.Commerce.Sdk.ScaleUnit.targets(90,7): error MSB4184:     "customPackagePublisher": "MANIFEST_CUSTOM_PUBLISHER",
C:\Users\XXX\.nuget\packages\microsoft.dynamics.commerce.sdk.scaleunit\9.30.21211.6\build\Microsoft.Dynamics.Commerce.Sdk.ScaleUnit.targets(90,7): error MSB4184:     "customPackageVersion": "MANIFEST_CUSTOM_VERSION"
C:\Users\XXX\.nuget\packages\microsoft.dynamics.commerce.sdk.scaleunit\9.30.21211.6\build\Microsoft.Dynamics.Commerce.Sdk.ScaleUnit.targets(90,7): error MSB4184: }
C:\Users\XXX\.nuget\packages\microsoft.dynamics.commerce.sdk.scaleunit\9.30.21211.6\build\Microsoft.Dynamics.Commerce.Sdk.ScaleUnit.targets(90,7): error MSB4184: ".Replace(MANIFEST_CUSTOM_PUBLISHER, CN=XXX, O=XXX, L=XXX, C=XX)" cannot be evaluated. Method 'System.String.Replace' not found.
1>Done building project "ScaleUnit.csproj" -- FAILED.
```

**Reproduction steps:**
1. Clone the ScaleUnit solution
2. Edit repo.props file chaning publisher to: CN=Contoso LTD, O=Contoso
3. Open ScaleUnit solution and build

**Suggested solution:** 
Encapsulate the value of %(CustomManifestDataToReplace.ReplacementValue) with single quotes in Microsoft.Dynamics.Commerce.Sdk.ScaleUnit.targets Line 90:
```
Lines="$([System.IO.File]::ReadAllText(
        $(ManifestFile)).Replace(%(CustomManifestDataToReplace.Identity), '%(CustomManifestDataToReplace.ReplacementValue)'))"
```

**Comment by andreesteve** [comment]
Thanks, @andyNewnham for reporting. I filled internal bug 615718 so we can get the right people to investigate this.

**Comment by mugunthanm** [comment]
@andyNewnham the fix in progress for this issue, soon we will release a hotfix for this.

**Comment by dadossan** [comment]
@andyNewnham the fix is available in the latest version of "Microsoft.Dynamics.Commerce.Sdk.ScaleUnit" 9.30.* onwards
