### ISSUE TITLE
Provide steps to debug CPOS and CommerceRuntime code together

### ISSUE THREAD

**Issue by vkommuri2897** [microsoft/Dynamics365Commerce.ScaleUnit#20]
Hi,
Is there any documentation to explain debug procedure for CPOS and CRT code? I wanted to run CPOS and debug CPOS and CRT code same time like RetailSDK.

**Comment by Pikhulya** [comment]
[Here](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/pos-extension/debug-pos-extension#run-and-debug-cloud-pos) you will find an information on how to debug CPOS extensions and [here](https://github.com/microsoft/Dynamics365Commerce.ScaleUnit/blob/release/9.40/src/ScaleUnitSample/Readme.md#debugging) the CRT/RS extensions.

**Comment by vkommuri2897** [comment]
I have followed above mentioned steps but it seems like it not same what i am expecting. I am using new Commerce SDK with headless commerce. Steps in above pointing to old SDK. Is there anyway we can have short call for the understanding? Please ping me any time in teams.

**Comment by Pikhulya** [comment]
@lukedgr - FYI

**Comment by lukedgr** [comment]
Hi @vkommuri2897 - the steps linked above are for the Commerce SDK. Please let us know if you have any specific questions on how to debug CRT or CPOS based on those steps.

**Comment by vkommuri2897** [comment]
Hi @lukedgr - I wanted to debug POS code by running CPOS client. Add break points in CPOS and CRT code and debug. How can i do this? Can you provide steps for the same?

**Comment by vkommuri2897** [comment]
Hi @lukedgr - I am also not able to complete CPOS debugging steps. Unable to link Extensions and Root directory.
![image](https://user-images.githubusercontent.com/111564235/189922724-0d13384d-117e-4fb6-ab6c-6d4e9a08f81c.png)

**Comment by lukedgr** [comment]
Hi @vkommuri2897 , can you please check if the CDSG.Commerce.MarkOutTrans file exists in the Pos/Extensions directory of the scale unit install?
