### ISSUE TITLE
Getting error Unable to load the extension package with new package 

### ISSUE THREAD

**Issue by vkommuri2897** [microsoft/Dynamics365Commerce.ScaleUnit#21]
Hi,
I have created new package using Dynamics365Commerce.ScaleUnit sample. Followed all necessary steps. But my custom package is not  loading. Can you help me to identify root cause?
![image](https://user-images.githubusercontent.com/111564235/189685989-7e25ddce-599b-4a49-9219-9087f1b54b8e.png)

**Comment by Pikhulya** [comment]
Please see if the Troubleshooting section from [here ](https://community.dynamics.com/ax/b/axforretail/posts/introducing-sealed-installers#mcetoc_1fh52t7kg0)helps.

**Comment by vkommuri2897** [comment]
Thank you. Above issue resolved.

**Comment by Pikhulya** [comment]
Closing since the resolution confirmation has been received.

@lukedgr  - FYI.
