### ISSUE TITLE
Compiler error with tsconfig.json

### ISSUE THREAD

**Issue by vkommuri2897** [microsoft/Dynamics365Commerce.ScaleUnit#22]
Hi @lukedgr - I am getting below error when i compile code in VS Code. It is not giving error with Visual Studio 2019. Do we need to ignore this error? If not what do i need to add to fix?
![image](https://user-images.githubusercontent.com/111564235/190131897-95622148-60b2-4053-8060-2ef41c85860b.png)

**Comment by vkommuri2897** [comment]
Hi @Pikhulya, @lukedgr  - Could you please comment on this issue?

**Comment by vkommuri2897** [comment]
FYI, I am not able to add breakpoint to POS code. Not sure if this is due to above error.
![image](https://user-images.githubusercontent.com/111564235/190305539-65b4cea9-3bf1-476c-a838-7cf0701c78fc.png)

**Comment by Pikhulya** [comment]
To get rid of the error you shared in the very first screenshot apply [this](https://www.typescriptlang.org/tsconfig#strict) to tsconfig.json:

{
  "compilerOptions": {
...
    **"strict": true,** 
...
  },

**Comment by vkommuri2897** [comment]
Hi @Pikhulya, If i enable strict then i am getting lot of compilation errors. I have tried this but it is causing all CRT errors. Please check the image.
![image](https://user-images.githubusercontent.com/111564235/191168341-73ab23d4-d05e-47a6-bfe4-4f89f1bfef81.png)

**Comment by Pikhulya** [comment]
@vkommuri2897 all those errors come from your extension code, right? If so - can you as experiment temporary remove your extension and recompile to confirm there will be no errors. If there will be no errors then it is a reliable indication you need to address the errors in your extension.

**Comment by Pikhulya** [comment]
@vkommuri2897 , I assume you followed the previously given recommendations and resolved an issue with your extension and I'm therefore planning to close this issue, please share an update if the above steps didn't help you resolve the issue.

**Comment by Pikhulya** [comment]
Marking as Closed since a recommendation was provided long time ago and there are no responses since then.
