### ISSUE TITLE
ScaleUnit Installer Cert Issues

### ISSUE THREAD

**Issue by Vekto** [microsoft/Dynamics365Commerce.ScaleUnit#24]
Receiving this error during health check after a trying to install a RSSU (sealed .28). 

An exception occurred while executing request. CorrelationId: ''. Ex: 'Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: Keyset does not exist
   at Microsoft.Dynamics.Retail.Cdx.RealtimeServiceClientLibrary.RealtimeServiceClient.ProcessInvokeResult(String methodName, String apiName, Int32 parameterCount, RetailTransactionServiceResponse response, Guid correlationId, RetailRealTimeServiceContractChannel channel, Boolean isAsyncCall, Exception& exception, Int32& resultCount, Int64 executionTimeInMs)

Was installed with a cert for each piece, (SSL, Async, RetailServer). We seemed to trace it to the permissions for the RSSU private key being assigned to the ASync cert instead of the RSSU cert.

![image](https://user-images.githubusercontent.com/11138147/193693331-24033709-c121-4604-ab23-fa17b4bf0019.png)

**Comment by Pikhulya** [comment]
What version of the Base Sealed Scale Unit Installer are you using? The issue around the certs was fixed in 10.0.30 starting the build 9.40.22197.19.

**Comment by Vekto** [comment]
We're using 10.0.28, specifically 9.38.22271.4, if it's been fixed already we'll just wait for that and we can close this.

Thank you

**Comment by Pikhulya** [comment]
@Vekto , thanks for the confirmation you experience that problem not in 10.0.30. Please note that that Preview of 10.0.30 is already available for download from the [LCS](https://lcs.dynamics.com/V2/SharedAssetLibrary):

![image](https://user-images.githubusercontent.com/11545082/194180505-9b6e64b0-927e-4db8-992e-de9b8cdefce2.png)
