### ISSUE TITLE
Typescript error - Cannot read properties of undefined

### ISSUE THREAD

**Issue by vkommuri2897** [microsoft/Dynamics365Commerce.ScaleUnit#25]
Hi,

I am getting below error with my view model. I am providing view model code below. I am not getting error if i do not extend CustomViewControllerBase in view model. What is the right procedure here.

**ERROR MESSAGE:**
Cannot read properties of undefined (reading 'CustomViewControllerBase') Evaluating https://localhost:446/POS/Extensions/CDSG.Commerce.InventItemBarcode/Views/PrintBarcode/PrintBarcodeViewModel.js Evaluating https://localhost:446/POS/Extensions/CDSG.Commerce.InventItemBarcode/Views/PrintBarcode/PrintBarcodeView.js Loading Extensions/CDSG.Commerce.InventItemBarcode/Views/PrintBarcode/PrintBarcodeView

**Code:**
####################################
import  Views from "PosApi/Create/Views";
import { ClientEntities } from "PosApi/Entities";
import { Entities } from "../../DataService/DataServiceEntities.g";
import { InventItemBarcodeController } from "../../DataService/DataServiceRequests.g";
//import ko from "knockout";
import { ObjectExtensions } from "PosApi/TypeExtensions";

export default class PrintBarcodeViewModel extends Views.CustomViewControllerBase {
    
    //public title: ko.Observable<string>;    
    public DataSource_ItemBarcodeList: Entities.InventItemBarcode[];

    constructor(context: Views.ICustomViewControllerContext) {
        super(context);        
        //this.title = ko.observable("Product Order");
        this.DataSource_ItemBarcodeList = [];
        this.refreshList();
    }

    public refreshList(): Promise<void> {
        this.state.isProcessing = true;  
        let req: InventItemBarcodeController.GetInventItemBarcodeListRequest<InventItemBarcodeController.GetInventItemBarcodeListResponse>
            = new InventItemBarcodeController.GetInventItemBarcodeListRequest<InventItemBarcodeController.GetInventItemBarcodeListResponse>();
        return this.context.runtime.executeAsync(req).then((responseVar: ClientEntities.ICancelableDataResult<InventItemBarcodeController.GetInventItemBarcodeListResponse>): Promise<void> => {
            if (!responseVar.canceled) {
                this.DataSource_ItemBarcodeList = responseVar.data.result;
                this.state.isProcessing = false;  
                return Promise.resolve();  
            }
            else {
                this.state.isProcessing = false;  
                return Promise.resolve();  
            }
        });
    }

    /**
 * The onReady function is called when the page element has been added to the DOM. It is responsible for binding the view controller to the element.
 * @param {HTMLElement} element The root element for the view.
 */
    public onReady(element: HTMLElement): void {
    }

    /**
    * The dispose method is called by the POS framework when the view is removed from the DOM and the navigation history.
    * It is important to release the view controller resources when it is disposed to prevent memory leaks.
    */
    public dispose(): void {
        ObjectExtensions.disposeAllProperties(this);
    }
}

**Comment by madyke** [comment]
I discussed this with Luke, and it sounds like this was most likely resolved through other communication channels. If this is still an active issue, please let us know and we can re-open it and provide assistance.
