### ISSUE TITLE
Package deployment to a tier-1 cloud hosted environemnt

### ISSUE THREAD

**Issue by pugupta05** [microsoft/Dynamics365Commerce.ScaleUnit#28]
Can the independent package created for Commerce SDK be deployed in a LCS based tier 1 cloud hosted environment similar to the older Retail SDK package? or the new packages can only be applied in tier 2 and higher-level environments with CSU?

**Comment by Pikhulya** [comment]
Assuming you are talking about on-prem products, such, as, for instance, Store Commerce, MPOS, CSU, Hardware Station, they are based on Sealed Installers and can be installed on any box which meets prerequisites requirements specific for a particular product outlined above. So, if you have access to your LCS hosted machines and can deploy there required prerequisites for a specific installer - you should be able to deploy those products.

**Comment by Pikhulya** [comment]
@pugupta05 , please confirm you are unblocked with the information provided in the previous comment so we could then close this issue.

**Comment by pugupta05** [comment]
@Pikhulya thanks, you can mark this close for now, will report back or open a new issues or conversation in forum if needed any other help here.
