### ISSUE TITLE
Unable to load the extension package

### ISSUE THREAD

**Issue by mmoalla** [microsoft/Dynamics365Commerce.ScaleUnit#31]
Hello,
I'm facing issue in cloud pos  **in cloud hosted VHD** : I download scale unit sample and build the project but when i put generated package files from scale unit project for both RetailServer and CloudPos and put dlls and extension on retail server and cloud pos folders ,  i get an error **Unable to load the extension package manifest not in package or incorrecly formatted**

I want to migrate retail sdk extension to Cormmerce SDK and to test if i work i download a vhd from lcs 10.0.29.

**Could you please how to load extended package in Commerce SDK in local Cloud hosted VHD  ?**

**Comment by Pikhulya** [comment]
Please check the section [Troubleshooting](https://community.dynamics.com/ax/b/axforretail/posts/introducing-sealed-installers#mcetoc_1fh52t7kg0), it is for MPOS but it might give you an idea how to investigate. The main difference is that you need to look for the logs in the browser's Console output seen when you activate (via F12 normally) Developer Tools.

**Comment by Pikhulya** [comment]
I assume the above answer unblocked you, please respond if that is not the case.

**Comment by Pikhulya** [comment]
Resolving as the recommendation was provided and there were no responses indicating the help is still needed for a long time.
