### ISSUE TITLE
Validate SDKVersion when to generate CloudScaleUnitExtensionPackage

### ISSUE THREAD

**Issue by mauroschnider** [microsoft/Dynamics365Commerce.ScaleUnit#32]
Hello, I have an extension in version 9.41. After compiling the solution, in the folder src\ScaleUnitSample\ScaleUnit\bin\Debug\netstandard2.0\CloudScaleUnitExtensionPackage, I see that the manifest.json file has the property "sdkVersion": "9.28.0.0"

I need check if sdkVersion is correct

Thank you

**Comment by dadossan** [comment]
Hi @mauroschnider, this bug was fixed as part of [release/9.43](https://github.com/microsoft/Dynamics365Commerce.ScaleUnit/tree/release/9.43). You can clone that branch and validate issue was fixed.

**Comment by mauroschnider** [comment]
Hi @dadossan, Thank you
