### ISSUE TITLE
Build Issue with Commerce SDK 9.43

### ISSUE THREAD

**Issue by sudarshan-onactuate** [microsoft/Dynamics365Commerce.ScaleUnit#33]
Summary
Describe the issue

getting error unable to build the solution file of Commerce SDK cloned from the latest branch of Microsoft https://github.com/microsoft/Dynamics365Commerce.ScaleUnit/tree/release/9.43

Commerce SDK Version:

Visual Studio/Visual Studio Code/MSBuild Version:

Does this happen every time the solution is built: yes with version 9.43

Name of Project with Error:

MSBuild Error:

Severity    Code    Description    Project    File    Line    Suppression State
Error    NETSDK1060    Error reading assets file: Error loading lock file 'K:\CommerceSDK\Dynamics365Commerce.ScaleUnit\src\ScaleUnitSample\POS\obj\project.assets.json' : Error reading '' at line 6018 column 25 : Error reading '' at line 6023 column 43 : '[9.43.-, 9.44.0)' is not a valid version string.    POS    C:\Program Files\dotnet\sdk\2.1.526\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets

Reproducing the Issue
Clone https://github.com/microsoft/Dynamics365Commerce.ScaleUnit/tree/release/9.43 and Run Build.

<img width="543" alt="image" src="https://user-images.githubusercontent.com/84920626/228003034-5d3d3f89-f885-412e-98d2-4ce097ebe746.png">

-->
Link to GitHub repo/solution where the issue is reproducible:

Clone https://github.com/microsoft/Dynamics365Commerce.ScaleUnit/tree/release/9.43 and Run Build.

<img width="542" alt="image" src="https://user-images.githubusercontent.com/84920626/228003323-addbad56-d87d-43b4-960b-450ed638cf92.png">

#https://github.com/microsoft/Dynamics365Commerce.Solutions/issues/38

**Comment by dadossan** [comment]
Hi @sudarshan-onactuate, what version of Visual Studio are you using? Note that the package versions consumed by the sample are defined as float versions as you can see on [repo.props](https://github.com/microsoft/Dynamics365Commerce.ScaleUnit/blob/release/9.43/repo.props). Float version resolutions are only supported on Visual Studio version 16.6 onwards as you can see in this [doc](https://learn.microsoft.com/en-us/nuget/concepts/package-versioning#floating-version-resolutions). Try building the sample on Visual Studio 19 or 22 and check if issue persists.

**Comment by Pikhulya** [comment]
I'm unable to reproduce the issue by using VS 2022 with all the updates and the latest I just got for 9.43. Given no responses for a long time to @dadossan 's ask - I'm closing this ticket.
