### ISSUE TITLE
Unable to build Scale Unit Project. 

### ISSUE THREAD

**Issue by AmanSonii** [microsoft/Dynamics365Commerce.ScaleUnit#4]
`Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3027	Could not copy "D:\Dynamics365Commerce.ScaleUnit-release-9.33\Dynamics365Commerce.ScaleUnit-release-9.33\src\ScaleUnitSample\POS\Controls\Dialogs\Create\ExampleCreateDialog.html" to "bin\Debug\netstandard2.0\CloudScaleUnitExtensionPackage\RetailCloudPOS\Code\Extensions\Contoso.Commerce\Controls\Dialogs\Create\ExampleCreateDialog.html". Exceeded retry count of 10. Failed. 	ScaleUnit	C:\Users\username\.nuget\packages\microsoft.dynamics.commerce.sdk.scaleunit\9.33.21349.5\build\Microsoft.Dynamics.Commerce.Sdk.ScaleUnit.targets	136	

Thanks,
Aman

**Comment by Pikhulya** [comment]
It looks like the file is hold by another process, please make sure to close command prompts, file explorers, debuggers and try again. If you are compiling by leveraging VS - close the VS and then reopen it.

**Comment by AmanSonii** [comment]
I am using visual studio 2019. I am getting "**Option 'project' cannot be mixed with source files on a command line.**"

**Comment by mugunthanm** [comment]
Adding @lukedgr . 

@AmanSonii - Can you please try with VS 2017, because POS is not supported with VS 2019.

**Comment by Pikhulya** [comment]
@AmanSonii are you unblocked and we could close this ticket or you still need help?

**Comment by AmanSonii** [comment]
Thanks @mugunthanm
