### ISSUE TITLE
Retail SDK packages availability

### ISSUE THREAD

**Issue by emishura** [microsoft/Dynamics365Commerce.ScaleUnit#5]
Hello,

Some of the packages that were available before in RetailSDK folder are not available in CommerceSDK NuGet feed (e.g. 
   - microsoft.dynamics.commerce.runtime.localization.services.9.32.21271.2.nupkg
   - microsoft.dynamics.commerce.runtime.services.9.32.21271.2.nupkg
   - microsoft.dynamics.commerce.runtime.services.pricingengine.9.32.21271.2.nupkg
 )
We are using some of the public classes from the following packages.
Will they be available also in the feed? Or do we need to recreate all of them in our custom solution and can't use any of the standard classes from these packages?

**Comment by Pikhulya** [comment]
An extension should not have dependencies on internal services implementations, it should only depend on contract, please refer to the [following ](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/crt-services#default-crt-services)section for details:
![image](https://user-images.githubusercontent.com/11545082/147635163-c7e0d9f2-7950-4065-bdd8-7cf2877dc54d.png)

**Comment by emishura** [comment]
Oki, thank you :)

**Comment by emishura** [comment]
What about Pricing engine samples that were provided in RetailSDK by Micorosoft?
They had references to Microsoft.Dynamics.Commerce.Runtime.Services package.
![image](https://user-images.githubusercontent.com/19534046/147661482-3c8e59e6-f8e6-4117-b584-a4a29f827ad2.png)
Will Microsoft provide any examples for similar extensions in CommerceSDK? Probably I just didn't find it
![image](https://user-images.githubusercontent.com/19534046/147661548-a5a3084f-0ff8-4091-8284-71363b6b52e7.png)

**Comment by mugunthanm** [comment]
Yes, we are working on the pricing package and samples for the new SDK, but it will take a few more months to get published.

**Comment by mugunthanm** [comment]
Yes, we are working on the pricing package and samples for the new SDK, but it will take a few more months to get published.

**Comment by Pikhulya** [comment]
@emishura if your questions/comments were addressed, we will close the ticket, please let us know if you still need more clarifications  regarding the topic.

**Comment by Pikhulya** [comment]
For the record, [here](https://www.yammer.com/dynamicsaxfeedbackprograms/threads/1547928521146368) is another discussion on this.

**Comment by rizworks** [comment]
Thanks for updating.

**Comment by Pikhulya** [comment]
Closing as the answers were provided and there were no objections marking this as Closed.
