### ISSUE TITLE
Is there any possibility to split the ChannelDatabase.sql script to many files?

### ISSUE THREAD

**Issue by Halldor10** [microsoft/Dynamics365Commerce.ScaleUnit#9]
Today we have a history of many sql scripts for updating the Channel database and a configuration that lists up these sql script files.

Do all scripts need to be copied into one sql file like in the example ChannelDatabase project or is there some logic that can control the order of the scripts, if there are many sql script files?

**Comment by rizworks** [comment]
@Halldor10 It's the same logic and you can create multiple files for the channel database.

https://github.com/microsoft/Dynamics365Commerce.ScaleUnit/tree/release/9.35/src/ScaleUnitSample

![image](https://user-images.githubusercontent.com/1855045/155433057-4aaf304c-1a31-4011-b434-b106c3d9399e.png)

**Comment by Pikhulya** [comment]
Closing as the right answer was already provided by @rizworks .
